name: SacredCellar
favicon: null
layout_spectrum: 0.6036020077299327
typography_spectrum: 0.5398336979560554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3985454870853573
  lightness: 0.7507241391576827
  saturation: 0.9658458367921412
  rhythmicContrast: 0.9227069502230734
purpose: []
